In [ ]:

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer






from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [34]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [35]:
df.shape

(891, 4)

In [36]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [37]:
df.isnull().sum()

Age         177
Pclass        0
Fare          0
Survived      0
dtype: int64

In [38]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [40]:
x_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [41]:
knn=KNNImputer(n_neighbors=5,weights='distance')
x_train_trf=knn.fit_transform(x_train)
x_test_trf=knn.transform(x_test)

In [42]:
pd.DataFrame(x_train_trf,columns=x_train.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  25.223022     3.0    8.7125
709  71.000000     1.0   49.5042
710  33.279590     1.0  221.7792
711  49.275927     1.0   25.9250

[712 rows x 3 columns]

In [43]:
lr=LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred=lr.predict(x_test_trf)
accuracy_score(y_test,y_pred)

0.7094972067039106

In [44]:

# Comparision with Simple Imputer --> mean

si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [45]:
lr=LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred=lr.predict(x_test_trf)
accuracy_score(y_test,y_pred)

0.7094972067039106